---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  communicator: ssh
  gui: false

provisioner:
  name: chef_solo

platforms:
  #- name: centos-6.5
  - name: centos-6.6
  #- name: centos-7.1
  #- name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[yum]
      - recipe[yum-epel]
      - recipe[apache2]
      - recipe[qpid::server]
      - recipe[mongodb::default]

      - recipe[pulp::repository]
      - recipe[pulp::server]
      - recipe[pulp::admin]
    attributes:
      pulp:
        admin:
          server:
            verify_ssl: false
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.10"}]
  - name: client
    run_list:
      - recipe[yum]
      - recipe[yum-epel]

      - recipe[pulp::repository]
      - recipe[pulp::client]
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.50"}]
